name: crossbuild windows

on:
  push:
    branches:
      - master

jobs:
  win-build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: 'git submodule update --init --recursive'

    - name: Build
      run: 'make; make describe'

    - name: Install MinGW toolchain
      run: 'sudo apt install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 -y'

    - name: Install 32-bit subsystem
      run: 'sudo dpkg --add-architecture i386; sudo apt update'

    - name: Install wine (32- and 64-bit both)
      run: 'sudo apt install wine32 wine64'

    - name: Regression tests
      run: 'DEV_MACHINE=1 HAS_32CDEFS=0 HAS_64CDEFS=0 make check'
