name: build macos

on:
  push:
    branches:
      - master

jobs:
  macos-build:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build with CI build script
      run: 'make describe check'
