name: build macos

on:
  push:
    branches:
      - master

jobs:
  macos-build:
    strategy:
      matrix:
        os: [ macos-12, macos-11 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update submodules
      run: 'git submodule update --init --recursive'

    - name: Build
      run: 'make'

    - name: Regression tests
      run: 'make describe check'
