name: build linux

on:
  push:
    branches:
      - master

jobs:
  linux-build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install gcc-multilib
      run: 'sudo apt update; sudo apt install gcc-multilib -y'

    - name: Build
      run: 'make'

    - name: Regression tests
      run: 'make describe check'
